# Custom Language File for Launcher Customizer

[ejs.app]
title = "Aurora Vitae Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaXURL = "https://x.com/AuroraVitaeSMP"
mediaInstagramURL = "https://www.tiktok.com/@auroravitaesmp"
mediaYouTubeURL = "https://www.youtube.com/@AuroraVitaeSMP"
mediaDiscordURL = "https://discord.gg/avsmp"

[ejs.settings]
sourceGithubLink = "https://github.com/oAccel/AuroraVitae"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "Seja bem-vindo(a) novo Assente!"
welcomeDescription = "É com muito prazer que apresentamos o Aurora Vitae Launcher, disponível somente aos dignos de coração"
welcomeDescCTA = "Desejar embarcar nessa história?"
