# Custom Language File for Launcher Customizer

[ejs.app]
title = "Helios Launcher"

[ejs.landing]
mediaGitHubURL = "https://www.tiktok.com/@auroravitaesmp"
mediaXURL = "https://x.com/AuroraVitaeSMP"
mediaInstagramURL = "https://www.tiktok.com/@auroravitaesmp"
mediaYouTubeURL = "https://www.youtube.com/@AuroraVitaeSMP"
mediaDiscordURL = "https://discord.gg/avsmp"

[ejs.settings]
sourceGithubLink = "https://github.com/oAccel/AuroraVitae"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "WELCOME TO AVSMP"
welcomeDescription = "#."
welcomeDescCTA = "You are just a few clicks away from AVSMP."
